[versions]
agp = "8.5.2"
kotlin = "2.3.20"
composeBom = "2024.09.01"
junit4 = "4.13.2"

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-animation-core = { group = "androidx.compose.animation", name = "animation-core" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-geometry = { group = "androidx.compose.ui", name = "ui-geometry" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
junit = { group = "junit", name = "junit", version.ref = "junit4" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
